# 指定使用 Node.js 环境
language: node_js

# 指定 Node.js 版本
node_js:
  - "stable"  # 使用最新的稳定版 Node.js

# 缓存 npm 和 pnpm 的依赖目录，以加快构建速度
cache:
  directories:
    - ~/.npm
    - ~/.pnpm-store

# 在安装依赖之前，安装 pnpm
before_install:
  - npm install -g pnpm

# 安装项目依赖
install:
  - pnpm install  # 使用 pnpm 安装依赖

# 运行构建脚本
script:
  - pnpm run build  # 使用 pnpm 运行构建脚本

# 如果需要，可以添加部署配置
# deploy:
#   ...
